### ISSUE TITLE
K-means - 2 potential changes to .test_input

### ISSUE THREAD

**Issue by derek-damron** [jmwerner/ArtisanalMachineLearning#5]
- That `k` is an integer.  E.g.

``` r
if(as.integer(k) != k){
    stop("k must be a positive integer!")
}
```
- Use `is.data.frame()` instead of `class()`.  The current method wouldn't allow you specify a data.table (or anything other multi-class object that inherits from data.frames), which may or may not be desired. :smile_cat: 

``` r
~~if(class(data) != "data.frame"){~~
if(!is.data.frame(data)){
    stop("Data must be a data.frame!")
}
```

**Comment by jmwerner** [comment]
I dig. Stank you!
